AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates Kittens Carousel static website application deployed on AWS Simple Storage Service (S3),
  served through Cloudfront and Route 53 using AWS Cloudformation Service.
Parameters:
  BucketName:
    Type: String
    Description: The name for the bucket hosting your website  
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicReadWrite
      BucketName: !Ref BucketName
      MetricsConfigurations: 
        - Id: EntireBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      WebsiteConfiguration:
        IndexDocument: index.html
  
  MyS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Sub: arn:aws:s3:::${MyS3Bucket}/*
  
  MyCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    DependsOn:
      - MyS3Bucket
    Properties:
      DistributionConfig:
        Enabled: true 
        HttpVersion: http2
        IPV6Enabled: true
        DefaultCacheBehavior:
          TargetOriginId:
            Ref: MyS3Bucket
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          Compress: false
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
            Headers:
            - Access-Control-Request-Headers
            - Access-Control-Request-Method
            - Origin 
        Origins: 
          - DomainName:
              Fn::GetAtt:
              - MyS3Bucket
              - RegionalDomainName
            Id:
              Ref: MyS3Bucket
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        ViewerCertificate: 
          AcmCertificateArn: arn:aws:acm:us-east-1:016356827677:certificate/6b86c554-f8bd-41d7-8608-337bbeef97fe
          MinimumProtocolVersion: TLSv1.2_2019 
          SslSupportMethod: sni-only

  MyRoute53Record:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
          DNSName: !GetAtt MyCloudFrontDistribution.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: Z0462905NHPX0P9Y9N2C
      Name: www.akmustafa.net #required
      Type: A #required

Outputs:
  WebsiteURL:
    Value: !GetAtt [MyS3Bucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [MyS3Bucket, DomainName]]]
    Description: Name of S3 bucket to hold website content
  CloudFrontDomain:
    Value:
      Fn::GetAtt:
        - MyCloudFrontDistribution
        - DomainName
    Description: Domain name of CloudFront to hold website content