version: "3"
services:
  database:
    image: mysql:5.7 
    environment: 
      MYSQL_ROOT_PASSWORD: R1234r
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet
  app:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - database
    networks: 
      - clarusnet
networks:
    clarusnet:
        driver: bridge