version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway_1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - clarusnet
    configs:
      - source: initialdatabase
        target: /docker-entrypoint-initdb.d/init.sql

  app-server:
    image: 046402772087.dkr.ecr.us-east-1.amazonaws.com/clarusway-repo/phonebook-app:latest
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: overlay

volumes:
  db-data:

configs:
  initialdatabase:
      file: ./init.sql
