AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run dynamic web site with Flask Web Frame
Resources:
  MustafaCFInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: secure
      SecurityGroups:
        - HTTPandSSH
      Tags:
        - Key: Name
          Value: Flask Web Server Roman Numerals Converter
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update -y
          sudo amazon-linux-extras install nginx1.12
          sudo systemctl start nginx
          sudo systemctl enable nginx
          cd /usr/share/nginx/html
          sudo chmod -R 777 /usr/share/nginx/html
          sudo rm index.html
          wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/100_kitten_carousel_static_website_ec2_ngnix/static-web/index.html
          wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/100_kitten_carousel_static_website_ec2_ngnix/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/100_kitten_carousel_static_website_ec2_ngnix/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/100_kitten_carousel_static_website_ec2_ngnix/static-web/cat2.jpg
          sudo systemctl restart nginx


          