AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run dynamic web site with Flask Web Frame
Resources:
  MustafaCFInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: secure
      SecurityGroups:
        - HTTPandSSH
      Tags:
        - Key: Name
          Value: Flask Web Server Roman Numerals Converter
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update -y
          sudo yum install python3 -y
          sudo pip3 install flask -y
          sudo wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/001-roman-numerals-converter/app.py
          sudo mkdir templates
          cd templates
          sudo wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/001-roman-numerals-converter/templates/index.html
          sudo wget https://raw.githubusercontent.com/Musti4096/aws_devops_workshop/master/aws/projects/001-roman-numerals-converter/templates/result.html
          cd ..
          sudo python3 app.py


          